const mayonnaise = require('mayonnaise.js');

console.log('sentence:', mayonnaise.sentence);
console.log('paragraph:', mayonnaise.sentences(4));
console.log('title:', mayonnaise.title);
console.log('text:', mayonnaise.text);
console.log('timecard:', mayonnaise.timecard);
console.log('description:', mayonnaise.description);
console.log('short_description:', mayonnaise.short_description);
console.log('string:', mayonnaise.string);
console.log('word:', mayonnaise.word);
console.log('words(7):', mayonnaise.words(7));
console.log('array_of_words(7):', mayonnaise.array_of_words(7));
console.log('letter:', mayonnaise.letter);
console.log('name:', mayonnaise.name);
console.log('username:', mayonnaise.username);
console.log('first_name:', mayonnaise.first_name);
console.log('last_name:', mayonnaise.last_name);
console.log('full_name:', mayonnaise.full_name);
console.log('catch_phrase:', mayonnaise.catch_phrase);
console.log('place:', mayonnaise.place);
console.log('location:', mayonnaise.location);
